command /opengui:
    permission: op
    permission message: Sorry, you cannot run this command!
    trigger:
        set {_gui} to chest inventory named "GUI" with 3 rows
        set slot 3 of {_gui} to grass block named "&bGrass Block"
        open {_gui} to player

on inventory click:
    if name of event-inventory is "GUI":
        if index of event-slot = 3:
            cancel event
            send "You cannot take the grass block, mom said its my turn" to player
